name       : python-pyelftools
version    : '0.28'
release    : 5
source     :
    - https://github.com/eliben/pyelftools/archive/refs/tags/v0.28.tar.gz : 56855d88ceb9dde60a189f473ca18fc5df9eee2843db93cda81500a911f9472f
homepage   : https://github.com/eliben/pyelftools
license    : Unlicense
component  : programming.python
summary    : Parsing ELF and DWARF in Python
description: |
    pyelftools is a pure-Python library for parsing and analyzing ELF files and DWARF debugging information.
build      : |
    %python3_setup
install    : |
    %python3_install
