name       : python-pyelftools
version    : 0.26
release    : 1
source     :
    - https://github.com/eliben/pyelftools/archive/v0.26.tar.gz : b11306aeb2c2d0cf253876cb889e457a0ba3cb56a3b92cd1867c902edccf6b0a
homepage   : https://github.com/eliben/pyelftools
license    : Unlicense
component  : programming.python
summary    : Parsing ELF and DWARF in Python
description: |
    pyelftools is a pure-Python library for parsing and analyzing ELF files and DWARF debugging information.
build      : |
    %python3_setup
install    : |
    %python3_install
