name       : python-pyelftools
version    : '0.29'
release    : 6
source     :
    - https://github.com/eliben/pyelftools/archive/refs/tags/v0.29.tar.gz : 591c2b5150f180937c60714a1ae288365b1a3d6ae68aaaa4503dd5ecf5e3c299
homepage   : https://github.com/eliben/pyelftools
license    : Unlicense
component  : programming.python
summary    : Parsing ELF and DWARF in Python
description: |
    pyelftools is a pure-Python library for parsing and analyzing ELF files and DWARF debugging information.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        python3 test/run_all_unittests.py
        python3 test/run_examples_test.py
    popd
