name       : python-pyelftools
version    : '0.27'
release    : 2
source     :
    - https://github.com/eliben/pyelftools/archive/v0.27.tar.gz : 2958edd7c32909f1d541b8122797fee903db700d02d168b2789aa6b667fc4a30
homepage   : https://github.com/eliben/pyelftools
license    : Unlicense
component  : programming.python
summary    : Parsing ELF and DWARF in Python
description: |
    pyelftools is a pure-Python library for parsing and analyzing ELF files and DWARF debugging information.
build      : |
    %python3_setup
install    : |
    %python3_install
